### ISSUE TITLE
Can't bind socket

### ISSUE THREAD

**Issue by picchiosat** [n7tae/ham-dht-tools#4]
Hi, I tried to install dvin-tools but both dht-get and dht-spider produce this error:

terminate called after throwing an instance of 'dht::DhtException'
  what():  DhtException occurred: Can't bind socket
Aborted

Roby IV3JDV

**Comment by n7tae** [comment]
Are you trying to run this from a machine that is already running *mrefd*? That won't work as both *mrefd* and each tool need to bind to UDP port 17171. You also can't run -get and -spider at the same time on the same machine.
